/**
 * carWashes.ts — DrivePass+
 * Единый реестр партнёрских автомоек Узбекистана.
 * Координаты проверены по Yandex Maps / Google Maps.
 * Используется в: Locations, GeoFenceGuard, SmartLoadBalancer, BookingFlow, Marketplace
 */

export interface CarWashLocation {
  id: string;
  name: string;
  address: string;
  city: string;
  district: string;
  phone: string;
  rating: number;
  reviews: number;
  hours: string;
  openNow: boolean;
  hasGreenCorridor: boolean;
  drivepassPartner: boolean;
  lat: number;
  lng: number;
  distanceKm: number;      // рассчитывается динамически, дефолт для Самарканда
  services: string[];
  boxesTotal: number;
}

// ────────────────────────────────────────────────────────────────────────────
// САМАРКАНД — 8 моек
// ────────────────────────────────────────────────────────────────────────────
const SAMARKAND: CarWashLocation[] = [
  {
    id: 'smr-001',
    name: 'AutoShine Premium',
    address: 'ул. Амира Темура, 42',
    city: 'Самарканд',
    district: 'Центр',
    phone: '+998 91 234 56 78',
    rating: 4.8,
    reviews: 312,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 39.6542,
    lng: 66.9597,
    distanceKm: 0.4,
    services: ['Экспресс', 'Стандарт', 'Премиум'],
    boxesTotal: 5,
  },
  {
    id: 'smr-002',
    name: 'ExpressWash Регистан',
    address: 'ул. Регистан, 15',
    city: 'Самарканд',
    district: 'Старый город',
    phone: '+998 91 345 67 89',
    rating: 4.6,
    reviews: 187,
    hours: '07:00 – 21:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 39.6550,
    lng: 66.9760,
    distanceKm: 1.2,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
  {
    id: 'smr-003',
    name: 'CleanWave Улугбека',
    address: 'пр. Мирзо Улугбека, 88',
    city: 'Самарканд',
    district: 'Улугбек',
    phone: '+998 91 456 78 90',
    rating: 4.7,
    reviews: 245,
    hours: '09:00 – 20:00',
    openNow: false,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 39.6610,
    lng: 66.9420,
    distanceKm: 1.8,
    services: ['Стандарт', 'Детейлинг'],
    boxesTotal: 4,
  },
  {
    id: 'smr-004',
    name: 'ProWash Сиаб',
    address: 'ул. Ходжа Нисрон, 28',
    city: 'Самарканд',
    district: 'Базар Сиаб',
    phone: '+998 91 567 89 01',
    rating: 4.5,
    reviews: 98,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 39.6625,
    lng: 66.9810,
    distanceKm: 2.1,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
  {
    id: 'smr-005',
    name: 'Crystal Auto',
    address: 'ул. Ташкентская, 56',
    city: 'Самарканд',
    district: 'Северный',
    phone: '+998 91 678 90 12',
    rating: 4.9,
    reviews: 421,
    hours: '00:00 – 24:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 39.6700,
    lng: 66.9550,
    distanceKm: 2.7,
    services: ['Экспресс', 'Стандарт', 'Премиум', 'Детейлинг'],
    boxesTotal: 6,
  },
  {
    id: 'smr-006',
    name: 'Aqua Drive Самарканд',
    address: 'ул. Дагбитская, 120',
    city: 'Самарканд',
    district: 'Дагбит',
    phone: '+998 93 112 44 55',
    rating: 4.4,
    reviews: 76,
    hours: '08:00 – 21:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 39.6430,
    lng: 66.9380,
    distanceKm: 3.0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
  {
    id: 'smr-007',
    name: 'Splash Авто',
    address: 'пр. Бунёдкор, 14',
    city: 'Самарканд',
    district: 'Юг',
    phone: '+998 90 455 33 22',
    rating: 4.3,
    reviews: 54,
    hours: '07:30 – 20:30',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 39.6350,
    lng: 66.9500,
    distanceKm: 3.4,
    services: ['Экспресс', 'Стандарт', 'Химчистка салона'],
    boxesTotal: 4,
  },
  {
    id: 'smr-008',
    name: 'GreenBox Premium',
    address: 'ул. Навои, 70',
    city: 'Самарканд',
    district: 'Навои',
    phone: '+998 91 777 88 99',
    rating: 4.8,
    reviews: 198,
    hours: '08:00 – 23:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 39.6580,
    lng: 66.9680,
    distanceKm: 1.5,
    services: ['Экспресс', 'Стандарт', 'Премиум', 'Детейлинг'],
    boxesTotal: 5,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// ТАШКЕНТ — 10 моек
// ────────────────────────────────────────────────────────────────────────────
const TASHKENT: CarWashLocation[] = [
  {
    id: 'tsh-001',
    name: 'Royal Car Wash',
    address: 'пр. Амира Темура, 68',
    city: 'Ташкент',
    district: 'Юнусабад',
    phone: '+998 71 200 11 22',
    rating: 4.9,
    reviews: 589,
    hours: '07:00 – 23:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 41.3111,
    lng: 69.2797,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум', 'Детейлинг'],
    boxesTotal: 8,
  },
  {
    id: 'tsh-002',
    name: 'Aqua Pro Tashkent',
    address: 'ул. Шота Руставели, 15',
    city: 'Ташкент',
    district: 'Мирабад',
    phone: '+998 71 233 44 55',
    rating: 4.7,
    reviews: 345,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 41.2955,
    lng: 69.2750,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум'],
    boxesTotal: 6,
  },
  {
    id: 'tsh-003',
    name: 'Fast Clean Чилонзор',
    address: 'ул. Бунёдкор, 42',
    city: 'Ташкент',
    district: 'Чилонзор',
    phone: '+998 71 277 66 88',
    rating: 4.5,
    reviews: 210,
    hours: '07:00 – 22:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 41.2850,
    lng: 69.2150,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 4,
  },
  {
    id: 'tsh-004',
    name: 'Mega Wash Сергели',
    address: 'ул. Янги Сергели, 88',
    city: 'Ташкент',
    district: 'Сергели',
    phone: '+998 71 288 99 11',
    rating: 4.4,
    reviews: 134,
    hours: '08:00 – 21:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 41.2380,
    lng: 69.2200,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Химчистка салона'],
    boxesTotal: 5,
  },
  {
    id: 'tsh-005',
    name: 'Premium Auto Spa',
    address: 'пр. Мустакиллик, 32',
    city: 'Ташкент',
    district: 'Яккасарай',
    phone: '+998 90 988 77 66',
    rating: 4.8,
    reviews: 467,
    hours: '00:00 – 24:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 41.3050,
    lng: 69.2580,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум', 'Детейлинг', 'Химчистка салона'],
    boxesTotal: 10,
  },
  {
    id: 'tsh-006',
    name: 'Express Wash Олмазор',
    address: 'ул. Олмазор, 16',
    city: 'Ташкент',
    district: 'Олмазор',
    phone: '+998 93 555 44 33',
    rating: 4.3,
    reviews: 89,
    hours: '07:30 – 21:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 41.3280,
    lng: 69.2350,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
  {
    id: 'tsh-007',
    name: 'CleanMaster Шайхонтохур',
    address: 'ул. Навои, 120',
    city: 'Ташкент',
    district: 'Шайхонтохур',
    phone: '+998 71 244 55 66',
    rating: 4.6,
    reviews: 278,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 41.3220,
    lng: 69.2680,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум'],
    boxesTotal: 5,
  },
  {
    id: 'tsh-008',
    name: 'AutoBoss Мирзо-Улугбек',
    address: 'ул. Мирзо Улугбека, 55',
    city: 'Ташкент',
    district: 'Мирзо Улугбек',
    phone: '+998 90 123 45 67',
    rating: 4.5,
    reviews: 156,
    hours: '07:00 – 23:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 41.3400,
    lng: 69.3350,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Детейлинг'],
    boxesTotal: 4,
  },
  {
    id: 'tsh-009',
    name: 'Diamond Wash Мирабад',
    address: 'ул. Мирабад, 8',
    city: 'Ташкент',
    district: 'Мирабад',
    phone: '+998 97 444 22 11',
    rating: 4.7,
    reviews: 312,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 41.2980,
    lng: 69.2850,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум', 'Детейлинг'],
    boxesTotal: 7,
  },
  {
    id: 'tsh-010',
    name: 'WashPoint Бектемир',
    address: 'ул. Бектемир, 34',
    city: 'Ташкент',
    district: 'Бектемир',
    phone: '+998 93 666 77 88',
    rating: 4.2,
    reviews: 67,
    hours: '08:00 – 20:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 41.2750,
    lng: 69.3450,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// БУХАРА — 3 мойки
// ────────────────────────────────────────────────────────────────────────────
const BUKHARA: CarWashLocation[] = [
  {
    id: 'bux-001',
    name: 'BukharaWash Central',
    address: 'ул. Накшбанди, 22',
    city: 'Бухара',
    district: 'Центр',
    phone: '+998 65 223 44 55',
    rating: 4.6,
    reviews: 134,
    hours: '08:00 – 21:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 39.7745,
    lng: 64.4225,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум'],
    boxesTotal: 4,
  },
  {
    id: 'bux-002',
    name: 'Ark Auto Clean',
    address: 'ул. Мустакиллик, 50',
    city: 'Бухара',
    district: 'Арк',
    phone: '+998 65 224 55 66',
    rating: 4.4,
    reviews: 87,
    hours: '07:30 – 20:30',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 39.7780,
    lng: 64.4150,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
  {
    id: 'bux-003',
    name: 'GoldWash Бухара',
    address: 'ул. Ибн Сино, 15',
    city: 'Бухара',
    district: 'Восток',
    phone: '+998 65 225 66 77',
    rating: 4.5,
    reviews: 102,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 39.7700,
    lng: 64.4350,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Детейлинг'],
    boxesTotal: 4,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// НАМАНГАН — 2 мойки
// ────────────────────────────────────────────────────────────────────────────
const NAMANGAN: CarWashLocation[] = [
  {
    id: 'nmn-001',
    name: 'NamanganWash #1',
    address: 'ул. Навои, 35',
    city: 'Наманган',
    district: 'Центр',
    phone: '+998 69 233 44 55',
    rating: 4.5,
    reviews: 78,
    hours: '08:00 – 21:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 40.9983,
    lng: 71.6726,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
  {
    id: 'nmn-002',
    name: 'Qo\'qon Avto Wash',
    address: 'ул. Истиклол, 12',
    city: 'Наманган',
    district: 'Юг',
    phone: '+998 69 234 55 66',
    rating: 4.3,
    reviews: 45,
    hours: '07:30 – 20:30',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 40.9950,
    lng: 71.6680,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 2,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// ФЕРГАНА — 2 мойки
// ────────────────────────────────────────────────────────────────────────────
const FERGANA: CarWashLocation[] = [
  {
    id: 'frg-001',
    name: 'FerganaWash Premium',
    address: 'ул. Ал-Фарғоний, 48',
    city: 'Фергана',
    district: 'Центр',
    phone: '+998 73 244 55 66',
    rating: 4.6,
    reviews: 112,
    hours: '08:00 – 22:00',
    openNow: true,
    hasGreenCorridor: true,
    drivepassPartner: true,
    lat: 40.3842,
    lng: 71.7870,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт', 'Премиум'],
    boxesTotal: 4,
  },
  {
    id: 'frg-002',
    name: 'SparkleWash Фергана',
    address: 'ул. Мустакиллик, 22',
    city: 'Фергана',
    district: 'Запад',
    phone: '+998 73 245 66 77',
    rating: 4.4,
    reviews: 67,
    hours: '07:00 – 21:00',
    openNow: true,
    hasGreenCorridor: false,
    drivepassPartner: true,
    lat: 40.3810,
    lng: 71.7800,
    distanceKm: 0,
    services: ['Экспресс', 'Стандарт'],
    boxesTotal: 3,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// ЭКСПОРТ
// ────────────────────────────────────────────────────────────────────────────

export const ALL_CAR_WASHES: CarWashLocation[] = [
  ...SAMARKAND,
  ...TASHKENT,
  ...BUKHARA,
  ...NAMANGAN,
  ...FERGANA,
];

export const CAR_WASHES_BY_CITY: Record<string, CarWashLocation[]> = {
  'Самарканд': SAMARKAND,
  'Ташкент': TASHKENT,
  'Бухара': BUKHARA,
  'Наманган': NAMANGAN,
  'Фергана': FERGANA,
};

export const CITY_CENTERS: Record<string, [number, number]> = {
  'Самарканд': [39.6550, 66.9600],
  'Ташкент':   [41.3111, 69.2797],
  'Бухара':    [39.7745, 64.4225],
  'Наманган':  [40.9983, 71.6726],
  'Фергана':   [40.3842, 71.7870],
};

export const TOTAL_PARTNER_WASHES = ALL_CAR_WASHES.length; // 25

/** Haversine distance in meters */
export function haversineMeters(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number }
): number {
  const R = 6_371_000;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const x =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x));
}
